# Generated by Django 5.0.2 on 2024-02-11 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
